### ISSUE TITLE
homebrew tap warnings

### ISSUE THREAD

**Issue by limed** [Versent/unicreds#43]
I'm seeing these warnings when using your homebrew tap

```
==> Tapping versent/taps
Cloning into '/usr/local/Library/Taps/versent/homebrew-taps'...

remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/versent/homebrew-taps/unicreds.rb:7:in `<class:Unicreds>'
Please report this to the versent/taps tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/versent/homebrew-taps/unicreds.rb:7:in `<class:Unicreds>'
Please report this to the versent/taps tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/versent/homebrew-taps/unicreds.rb:7:in `<class:Unicreds>'
Please report this to the versent/taps tap!

Tapped 1 formula (29 files, 20.3K)
```

Looks like its not you just need to switch this line:

```
sha1 '70bfdfd9491cec74916d44d29398d0650292fd1e
```

To use sha256 instead

**Comment by limed** [comment]
Based on the URL in the formula the sha 256 sum is:

```
$ shasum -a 256 unicreds_1.4.0_darwin_x86_64.tgz
34fe09adaed63b54dd6334447f0824a4d73957bcb473fd2c3b1b1eb015c2ebb0  unicreds_1.4.0_darwin_x86_64.tgz
```

**Comment by wolfeidau** [comment]
Gday I have updated the taps.

Because I haven't released a new version those who already have the tap need to do as follows to test this:
```
brew remove unicreds
brew untap versent/taps
brew tap versent/taps
brew install unicreds
```

Now no warnings!

Cheers
